version: "1"

services:
  - type: web
    name: ekvidya-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install && npm run build && npx prisma db push && npx prisma db seed
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ekvidya-db
          property: connectionString
      - key: JWT_SECRET
        value: ekvidya_sih26238_jwt_secret_key_super_secure_123
      - key: JWT_REFRESH_SECRET
        value: ekvidya_sih26238_refresh_secret_key_456
      - key: ENCRYPTION_KEY
        value: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: ekvidya-db
    databaseName: ekvidya_db
    user: ekvidya_user
    plan: free
    region: oregon
